-- Spam Numbers Table
CREATE TABLE IF NOT EXISTS spam_numbers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phone VARCHAR(20) NOT NULL UNIQUE,
    spam_score INT DEFAULT 0,
    report_count INT DEFAULT 0,
    category ENUM('spam', 'fraud', 'scam', 'telemarketing', 'other') DEFAULT 'spam',
    is_active BOOLEAN DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_phone (phone),
    INDEX idx_spam_score (spam_score),
    INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Spam Reports Table
CREATE TABLE IF NOT EXISTS spam_reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phone VARCHAR(20) NOT NULL,
    reporter_id INT,
    reason TEXT NOT NULL,
    category ENUM('spam', 'fraud', 'scam', 'telemarketing', 'other') DEFAULT 'spam',
    status ENUM('pending', 'verified', 'rejected') DEFAULT 'pending',
    reviewed_by INT,
    reviewed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_phone (phone),
    INDEX idx_status (status),
    INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Geolocation Table (for dial code to country/region mapping)
CREATE TABLE IF NOT EXISTS geolocation (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dial_code VARCHAR(10) NOT NULL UNIQUE,
    country_name VARCHAR(100) NOT NULL,
    country_iso VARCHAR(3) NOT NULL,
    continent VARCHAR(50),
    region VARCHAR(100),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_dial_code (dial_code),
    INDEX idx_country_iso (country_iso)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert sample geolocation data
INSERT INTO geolocation (dial_code, country_name, country_iso, continent, region) VALUES
('1', 'United States', 'US', 'North America', 'Northern America'),
('1', 'Canada', 'CA', 'North America', 'Northern America'),
('33', 'France', 'FR', 'Europe', 'Western Europe'),
('44', 'United Kingdom', 'GB', 'Europe', 'Northern Europe'),
('49', 'Germany', 'DE', 'Europe', 'Western Europe'),
('39', 'Italy', 'IT', 'Europe', 'Southern Europe'),
('34', 'Spain', 'ES', 'Europe', 'Southern Europe'),
('31', 'Netherlands', 'NL', 'Europe', 'Western Europe'),
('41', 'Switzerland', 'CH', 'Europe', 'Western Europe'),
('43', 'Austria', 'AT', 'Europe', 'Western Europe'),
('32', 'Belgium', 'BE', 'Europe', 'Western Europe'),
('351', 'Portugal', 'PT', 'Europe', 'Southern Europe'),
('46', 'Sweden', 'SE', 'Europe', 'Northern Europe'),
('47', 'Norway', 'NO', 'Europe', 'Northern Europe'),
('45', 'Denmark', 'DK', 'Europe', 'Northern Europe'),
('358', 'Finland', 'FI', 'Europe', 'Northern Europe'),
('352', 'Luxembourg', 'LU', 'Europe', 'Western Europe'),
('353', 'Ireland', 'IE', 'Europe', 'Northern Europe'),
('354', 'Iceland', 'IS', 'Europe', 'Northern Europe'),
('225', 'Côte d''Ivoire', 'CI', 'Africa', 'Western Africa'),
('221', 'Senegal', 'SN', 'Africa', 'Western Africa'),
('223', 'Mali', 'ML', 'Africa', 'Western Africa'),
('224', 'Guinea', 'GN', 'Africa', 'Western Africa'),
('226', 'Gambia', 'GM', 'Africa', 'Western Africa'),
('227', 'Niger', 'NE', 'Africa', 'Western Africa'),
('228', 'Togo', 'TG', 'Africa', 'Western Africa'),
('229', 'Benin', 'BJ', 'Africa', 'Western Africa'),
('233', 'Ghana', 'GH', 'Africa', 'Western Africa'),
('234', 'Nigeria', 'NG', 'Africa', 'Western Africa'),
('235', 'Chad', 'TD', 'Africa', 'Central Africa'),
('236', 'Central African Republic', 'CF', 'Africa', 'Central Africa'),
('237', 'Cameroon', 'CM', 'Africa', 'Central Africa'),
('238', 'Cabo Verde', 'CV', 'Africa', 'Western Africa'),
('239', 'São Tomé and Príncipe', 'ST', 'Africa', 'Central Africa'),
('240', 'Equatorial Guinea', 'GQ', 'Africa', 'Central Africa'),
('241', 'Gabon', 'GA', 'Africa', 'Central Africa'),
('242', 'Republic of the Congo', 'CG', 'Africa', 'Central Africa'),
('243', 'Democratic Republic of the Congo', 'CD', 'Africa', 'Central Africa'),
('244', 'Angola', 'AO', 'Africa', 'Southern Africa'),
('245', 'Guinea-Bissau', 'GW', 'Africa', 'Western Africa'),
('248', 'Seychelles', 'SC', 'Africa', 'Eastern Africa'),
('249', 'Rwanda', 'RW', 'Africa', 'Eastern Africa'),
('250', 'Burundi', 'BI', 'Africa', 'Eastern Africa'),
('251', 'Ethiopia', 'ET', 'Africa', 'Eastern Africa'),
('252', 'Somalia', 'SO', 'Africa', 'Eastern Africa'),
('253', 'Djibouti', 'DJ', 'Africa', 'Eastern Africa'),
('254', 'Kenya', 'KE', 'Africa', 'Eastern Africa'),
('255', 'Tanzania', 'TZ', 'Africa', 'Eastern Africa'),
('256', 'Uganda', 'UG', 'Africa', 'Eastern Africa'),
('257', 'Burundi', 'BI', 'Africa', 'Eastern Africa'),
('258', 'Mozambique', 'MZ', 'Africa', 'Eastern Africa'),
('260', 'Zambia', 'ZM', 'Africa', 'Southern Africa'),
('261', 'Madagascar', 'MG', 'Africa', 'Eastern Africa'),
('262', 'Réunion', 'RE', 'Africa', 'Eastern Africa'),
('263', 'Zimbabwe', 'ZW', 'Africa', 'Southern Africa'),
('264', 'Namibia', 'NA', 'Africa', 'Southern Africa'),
('265', 'Malawi', 'MW', 'Africa', 'Southern Africa'),
('266', 'Lesotho', 'LS', 'Africa', 'Southern Africa'),
('267', 'Botswana', 'BW', 'Africa', 'Southern Africa'),
('268', 'Eswatini', 'SZ', 'Africa', 'Southern Africa'),
('269', 'Comoros', 'KM', 'Africa', 'Eastern Africa'),
('27', 'South Africa', 'ZA', 'Africa', 'Southern Africa'),
('290', 'Saint Helena', 'SH', 'Africa', 'Western Africa'),
('291', 'Eritrea', 'ER', 'Africa', 'Eastern Africa'),
('297', 'Morocco', 'MA', 'Africa', 'Northern Africa'),
('298', 'Western Sahara', 'EH', 'Africa', 'Northern Africa'),
('299', 'Mauritania', 'MR', 'Africa', 'Western Africa');
